import type { MetadataRoute } from "next";

/**
 * Web app manifest: what "Add to Home screen" uses for the name, colours and
 * icon. The icons are generated by `npm run icons` from the same design as the
 * favicon and the Android app icon.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Promptbook",
    short_name: "Promptbook",
    description: "Collect, tag and search the AI prompts that actually work.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0c12",
    theme_color: "#0a0c12",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
