#!/usr/bin/env node
/**
 * Writes www/config.js from app.config.json. Runs before every `cap sync`.
 *
 * The offline page (www/error.html) is served from inside the app, not from
 * the site, so on its own it has no idea where "back to the site" is. This
 * hands it the URL, so its Retry button — and the automatic retry when the
 * connection returns — know where to go.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const { serverUrl = "" } = JSON.parse(await readFile(path.join(root, "app.config.json"), "utf8"));

if (serverUrl) {
  let url;
  try {
    url = new URL(serverUrl);
  } catch {
    console.error(`\napp.config.json: serverUrl "${serverUrl}" is not a valid URL.\n`);
    process.exit(1);
  }
  if (url.protocol !== "https:" && url.protocol !== "http:") {
    console.error(`\napp.config.json: serverUrl must start with https:// (got ${url.protocol}).\n`);
    process.exit(1);
  }
}

await writeFile(
  path.join(root, "www", "config.js"),
  `// Generated by scripts/prepare-www.mjs from app.config.json — do not edit.\n` +
    `window.PROMPTBOOK_URL = ${JSON.stringify(serverUrl)};\n`,
);

console.log(
  serverUrl
    ? `Site URL: ${serverUrl}`
    : "No serverUrl in app.config.json — the app will show its setup page until one is set.",
);
